export const apps = [
  {
    name: "Raycast",
    description: "That emoji picker takes 2 years to load and you've got things to say.",
    useCase: "For when that emoji picker takes 2 years to load and you've got things to say.",
    features: [
      "Opt + Space: search emojis instantly",
      "Cmd + Space + C: summon the color picker",
      "Cmd + Space + B: open my bookmarks",
      "Beautiful calculator",
      "Confetti. Yes, actual confetti.",
    ],
    tags: ["Free"],
    setupSince: "2022",
    delightMeter: 8,
    icon: "R",
  },
  {
    name: "CleanShot X",
    description:
      "Pinning things to your screen, taking and annotating screenshots, sharing your screenshots with a personal domain",
    useCase: "You need that screenshot to stick around longer than a second.",
    features: [
      "Cmd + Shift + 2: extract text from any part of the screen",
      "Cmd + Shift + 4: take + annotate screenshots, save as reusable design docs",
      "Cmd + Shift + 5: record videos/gifs with audio, cursor, webcam, and more",
      "Share everything instantly via my custom domain (ss.garysmith.me)",
    ],
    tags: ["Paid", "Setapp"],
    setupSince: "2019",
    delightMeter: 10,
    icon: "C",
  },
  {
    name: "Bartender",
    description: "Organizing your menu bar",
    useCase: "Your menu bar looks like Times Square and you just want peace.",
    features: [
      "Organizing menu bar icons into primary/secondary rows",
      "Adding spacers for clarity",
      "Hiding what I don't need until I need it",
    ],
    tags: ["Paid", "Setapp"],
    setupSince: "2019",
    delightMeter: 7,
    icon: "B",
  },
  {
    name: "One Switch",
    description: "You need to wipe your computer down but don't want to shut down your whole universe to do it.",
    useCase: "You need to wipe your computer down but don't want to shut down your whole universe to do it.",
    features: [
      "Quick toggles: show hidden files, enable screen clean mode, prevent sleep",
      "Amphetamine is a solid free alternative",
    ],
    tags: ["Paid", "Setapp"],
    setupSince: "2020",
    delightMeter: 5,
    icon: "O",
  },
  {
    name: "SideNotes",
    description: "BEST place for taking quick notes on your computer",
    useCase: "You need to jot something down right now.",
    features: [
      "My primary quick-thought-capture app",
      "Has folders + markdown, but keeps things calm and low-pressure",
      "I have weekly cleanups → some notes move, most notes die here. That's the beauty.",
    ],
    tags: ["Paid", "Setapp"],
    setupSince: "2019",
    delightMeter: 15,
    icon: "S",
  },
  {
    name: "Fantastical",
    description: "You just want to add something to your calendar like a human.",
    useCase: "You just want to add something to your calendar like a human.",
    features: [
      "My primary calendar app for personal events",
      "Natural language event entry in the menubar saves me ungodly amounts of time",
      "Setup is a bit much, and I still use Google Calendar for scheduling, but Fantastical is home for me.",
    ],
    tags: ["Freemium"],
    setupSince: "2017",
    delightMeter: 10,
    icon: "F",
  },
  {
    name: "Unclutter",
    description: "Place for your screenshots, important notes, and clipboard history",
    useCase: "You need a smart junk drawer for notes, clips, and screenshots.",
    features: [
      "Clipboard history: saves me daily oopsies",
      "Drag-and-drop file stash: where all my screenshots go",
      "Notes pane: long-term parking for ideas that don't need SideNotes",
    ],
    tags: ["Paid"],
    setupSince: "2019",
    delightMeter: 10,
    icon: "U",
  },
  {
    name: "Downie",
    description: "You need to download something… and the site really doesn't want you to.",
    useCase: "You need to download something… and the site really doesn't want you to.",
    features: [
      "Downloading YouTube videos, audio clips, and Instagram posts",
      "Works like magic on stuff with no download button",
    ],
    tags: ["Setapp", "Paid"],
    setupSince: "2019",
    delightMeter: 6,
    icon: "D",
  },
  {
    name: "Rectangle",
    description: "For organizing your windows to the sides on your screen",
    useCase: "You want side-by-side apps without the awkward gaps.",
    features: [
      "Window snapping, tiling, and full-screening without full-screen mode",
      "Rectangle + Mission Control = elite multitasking",
    ],
    tags: ["FREE"],
    setupSince: "2018",
    delightMeter: 7,
    icon: "R",
  },
  {
    name: "IINA",
    description: "You want to watch a video on your Mac and actually enjoy the experience before pressing play.",
    useCase: "You want to watch a video on your Mac and actually enjoy the experience before pressing play.",
    features: [
      "A modern media player that doesn't feel like it was built in 2004",
      "Plays anything you throw at it - subs, speed control, audio tweaks, all of it",
      "My go-to for downloaded lectures, screencasts, and movie nights",
    ],
    tags: ["FREE"],
    setupSince: "2018",
    delightMeter: 5,
    icon: "I",
  },
  {
    name: "Permute",
    description: "You need to convert one thing into another thing so you can upload it to the right thing.",
    useCase: "You need to convert one thing into another thing so you can upload it to the right thing.",
    features: [
      "Extracting audio from videos",
      "Resizing GIFs and compressing video",
      "Turning anything into everything else — like a Swiss Army encoder",
    ],
    tags: ["Setapp", "Paid"],
    setupSince: "2019",
    delightMeter: 5,
    icon: "P",
  },
  {
    name: "coconutBattery",
    description: "For monitoring your battery health every now and then",
    useCase: "You need to know if your battery is dying – or if it's just you.",
    features: [
      "Quick check on battery health, cycles, and age",
      "Plug in your iPhone/iPad to check those, too",
      "Great reality check when your laptop dies mid-Zoom and you want to blame someone.",
    ],
    tags: ["FREE"],
    setupSince: "2021",
    delightMeter: 6,
    icon: "C",
  },
]
